version: '3'
services:
  web:
    build: .
    ports:
    - "5000:5000"
    environment:
    - PORT=5000
    - REDIS_HOST=redis
    volumes:
    - .:/home/app
    - /var/run/docker.sock:/var/run/docker.sock
    links:
    - redis
    command: ["yarn", "start"]
  redis:
    image: redis